local dUtil = require 'dUtil.init'
local tableHelper = require 'tes3mp.util.table'
tableHelper.print(dUtil)

return dUtil.table(dUtil.tableType.HASH, nil, {
  ApparatusType = {
    MortarAndPestle = 0,
    Alembic = 1,
    Calcinator = 2,
    Retort = 3,
  },
  ArmorType = {
    Helmet = 0,
    Cuirass = 1,
    LeftPauldron = 2,
    RightPauldron = 3,
    Greaves = 4,
    Boots = 5,
    LeftGauntlet = 6,
    RightGauntlet = 7,
    Shield = 8,
    LeftBracer = 9,
    RightBracer = 10,
  },
  AttributeId = {
    None = -1,
    Strength = 0,
    Intelligence = 1,
    Willpower = 2,
    Agility = 3,
    Speed = 4,
    Endurance = 5,
    Personality = 6,
    Luck = 7
  },
  BipedObjectType = {
    Head = 0,
    Hair = 1,
    Neck = 2,
    Chest = 3,
    Groin = 4,
    Skirt = 5,
    RightHand = 6,
    LeftHand = 7,
    RightWrist = 8,
    LeftWrist = 9,
    Shield = 10,
    RightForearm = 11,
    LeftForearm = 12,
    RightUpperArm = 13,
    LeftUpperArm = 14,
    RightFoot = 15,
    LeftFoot = 16,
    RightAnkle = 17,
    LeftAnkle = 18,
    RightKnee = 19,
    LeftKnee = 20,
    RightUpperLeg = 21,
    LeftUpperLeg = 22,
    RightPauldron = 23,
    LeftPauldron = 24,
    Weapon = 25,
    Tail = 26,
  },
  BodypartId = {
    Head = 0,
    Hair = 1,
    Neck = 2,
    Chest = 3,
    Groin = 4,
    Hand = 5,
    Wrist = 6,
    Forearm = 7,
    UpperArm = 8,
    Foot = 9,
    Ankle = 10,
    Knee = 11,
    UpperLeg = 12,
    Clavicle = 13,
    Tail = 14,
  },
  BodypartType = {
    Skin = 0,
    Clothing = 1,
    Armor = 2,
  },
  SkillId = {
    None = -1,
    Block = 0,
    Armorer = 1,
    MediumArmor = 2,
    HeavyArmor = 3,
    BluntWeapon = 4,
    LongBlade = 5,
    Axe = 6,
    Spear = 7,
    Athletics = 8,
    Enchant = 9,
    Destruction = 10,
    Alteration = 11,
    Illusion = 12,
    Conjuration = 13,
    Mysticism = 14,
    Restoration = 15,
    Alchemy = 16,
    Unarmored = 17,
    Security = 18,
    Sneak = 19,
    Acrobatics = 20,
    LightArmor = 21,
    ShortBlade = 22,
    Marksman = 23,
    Mercantile = 24,
    Speechcraft = 25,
    HandToHand = 26,
  }
})
