local dUtil = require 'dUtil.init'

return dUtil.table(dUtil.tableType.HASH, nil, {
  ApparatusType = {
    MortarAndPestle = 0,
    Alembic = 1,
    Calcinator = 2,
    Retort = 3,
  },
  ArmorType = {
    Helmet = 0,
    Cuirass = 1,
    LeftPauldron = 2,
    RightPauldron = 3,
    Greaves = 4,
    Boots = 5,
    LeftGauntlet = 6,
    RightGauntlet = 7,
    Shield = 8,
    LeftBracer = 9,
    RightBracer = 10,
  },
  BipedObjectType = {
    Head = 0,
    Hair = 1,
    Neck = 2,
    Chest = 3,
    Groin = 4,
    Skirt = 5,
    RightHand = 6,
    LeftHand = 7,
    RightWrist = 8,
    LeftWrist = 9,
    Shield = 10,
    RightForearm = 11,
    LeftForearm = 12,
    RightUpperArm = 13,
    LeftUpperArm = 14,
    RightFoot = 15,
    LeftFoot = 16,
    RightAnkle = 17,
    LeftAnkle = 18,
    RightKnee = 19,
    LeftKnee = 20,
    RightUpperLeg = 21,
    LeftUpperLeg = 22,
    RightPauldron = 23,
    LeftPauldron = 24,
    Weapon = 25,
    Tail = 26,
  },
  BodypartType = {
    Skin = 0,
    Clothing = 1,
    Armor = 2,
  },
})
