---@meta

---@alias CellAmbientConstructor fun(ambientColor: Vector3, fogColor: Vector3, sunlightColor: Vector3, fogDensity: number): CellAmbient

--- L10N searcher function that retains a cached reference to a localization context, and returns matching values from that localization context when called.
--- Takes an optional params hashmap for parameter replacement in localized strings.
---@alias L10NSearchFunction fun(keyName: string, params: table<string, string>?): string

---@alias Vector3Constructor fun(x: number, y: number, z: number): Vector3

---@alias WeaponAttackConstructor fun(chopMin: integer, chopMax: integer, slashMin: integer, slashMax: integer, thrustMin: integer, thrustMax: integer): WeaponAttack

---@class tablelib
---@field isarray fun(inTable: table): boolean Returns true for pure lua array-like tables and false otherwise
---@field isempty fun(inTable: table): boolean Returns true when the given Lua table contains neither non-nil array elements nor non-nil key-value pairs, or false otherwise.
---@field nkeys fun(inTable: table): integer Returns the total number of elements in a given Lua table (i.e. from both the array and hash parts combined).
---@field clone fun(inTable: table): table Returns a shallow copy of the given Lua table.
---@field new fun(numArray: integer, numHash: integer): table This creates a pre-sized table, just like the C API equivalent lua_createtable(). This is useful for big tables if the final table size is known and automatic table resizing is too expensive.
---@field clear fun(tab: table) This clears all keys and values from a table, but preserves the allocated array/hash sizes. This is useful when a table, which is linked from multiple places, needs to be cleared and/or when recycling a table for use by the same context. This avoids managing backlinks, saves an allocation and the overhead of incremental array/hash part growth. Please note, this function is meant for very specific situations. In most cases it's better to replace the (usually single) link with a new table and let the GC do its work.

---@class DefaultInterfaces
---@field Color ColorModule?
---@field ClientVariableScopes ClientVariableScopes
---@field contentFixer ContentFixer
---@field customCommandHooks CustomCommandHooksInterface
---@field customEventHooks CustomEventHooks
---@field menuHelper MenuHelper
---@field scriptLoader DScriptLoaderHidden
---@field speechHelper SpeechHelper
---@field dreamDice DiceInterface?
---@field customMerchantRestock RestockInterface?
---@field recordStores RecordInterface?
---@field tes3 table<string, function>?
---@field timed TimedModule

---@class DreamWeaveMenuModule
---@field display function(pid: PlayerId, menuName: string)

---@class DreamWeaveScriptEnv
---@field print fun(...) Standard lua print
---@field string stringlib
---@field math mathlib
---@field menu DreamWeaveMenuModule
---@field tes3mp TES3MPModule global tes3mp namespace functions
---@field I table<string, table<any, any>> Global script interfaces to be accessed by other mods

---@class DUtilModule
---@field cellAmbient CellAmbientConstructor
---@field getRequiredDataFiles fun(): DataFileRequirements Safer version of below function which doesn't modify global server state
---@field loadRequiredDataFiles fun(writeLog: boolean): DataFileRequirements Loads the required data files, whilst also initializing the server connection requirements. ONLY Call this once!
---@field misc DUtilMisc
---@field transform TransformConstructor
---@field vector3 Vector3Constructor
---@field weaponAttack WeaponAttackConstructor

---@class SaveSubscriptionData
---@field filePath string Path of the file, relative to `server/data`, eg, `custom/myData.json`
---@field persistent boolean Whether or not to flush the data immediately after it's been saved, or keep it around
---@field data table<any, any> A persistent reference to the table to be saved. It must never be replaced!
---@field delay integer? Time in seconds between writes. This includes how long before the data is first saved.
---@field condition? fun(): boolean An optional condition function to run before determining whether or not to save.
---@field lastCheckedTime integer? The last time in seconds the subscription was checked for a save. Should NEVER be provided by the constructor! You will trip an assertion if you provide this asa parameter.

--- Special timer callback class generated by the timed module
--- Callbacks must be registered and are type-checked upon registration
---@class TimerCallback
---@field arguments any[] When registering a TimerCallback, you may provide arguments which then are fed into the function when it is called
---@field triggerAt integer The exact time at which the callback should fire. Defined when the callback is registered.
---@field callback function

---@class TES3MPCommandRegistration
---@field callback CommandHandler
---@field nameRequirement string[]?
---@field rankRequirement integer?

---@class TES3MPScriptRegistration
---@field interface table<any, any>? Exposed functions and variables for other scripts to access
---@field interfaceName string? Name of the interface for another script to look for. Mandatory if an interface is defined.
---@field eventHandlers table<string, function>? series of eventHandlers for this script to run
---@field eventValidators table<string, function>? series of eventValidators for this script to run
---@field chatCommands table<string, TES3MPCommandRegistration>? chat commands registered by this script
---@field menus table<string, TES3MPMenu>? Menus defined to be consumed by menuHelper

---@class Transform
---@field rotation Vector3
---@field position Vector3
---@field scale number

---@alias TransformConstructor fun(pos: Vector3, rot: Vector3, scale: number?): Transform Constructs a transform using FFI structs with Vector3 inputs. Used primarily for instance loading.

---@class Vector3: userdata
---@field x number
---@field y number
---@field z number
---@field __add fun(a: Vector3, b: Vector3): Vector3 add another vector onto this one
---@field __sub fun(a: Vector3, b: Vector3): Vector3 subtract another vector from this one
---@field __div fun(a: Vector3, b: Vector3): Vector3 divide this vector element-wise by a single number or another Vector3
---@field __mul fun(a: Vector3, b: Vector3): Vector3 multiply this vector element-wise by a single number or another Vector3
---@field __len fun(): number return the length of the vector
---@field normalize fun(): Vector3 returns the magnitude of the vector from 0.0-1.0
---@field is fun(v: any): boolean returns whether or not the input is also a vector3
---@field add_mut fun(v: Vector3) adds one vector onto this one mutably
---@field sub_mut fun(v: Vector3) subtract another vector from this one mutably
