---@meta

---@alias AIPackage
---| AIActivate
---| AIEscort
---| AIFollow
---| AITravel
---| AIWander

---@alias ApparatusType
---| 'MortarAndPestle' # 0
---| 'Alembic' # 1
---| 'Calcinator' # 2
---| 'Retort' # 3

---@alias ArmorType
---| 'Helmet' 0
---| 'Cuirass' 1
---| 'LeftPauldron' 2
---| 'RightPauldron' 3
---| 'Greaves' 4
---| 'Boots' 5
---| 'LeftGauntlet' 6
---| 'RightGauntlet' 7
---| 'Shield' 8
---| 'LeftBracer' 9
---| 'RightBracer' 10

---@alias AttributeId2
---| 'None' -1
---| 'Strength' 0
---| 'Intelligence' 1
---| 'Willpower' 2
---| 'Agility' 3
---| 'Speed' 4
---| 'Endurance' 5
---| 'Personality' 6
---| 'Luck' 7

---@alias BipedObjectType
---| 0 # 'Head'
---| 1 # 'Hair'
---| 2 # 'Neck'
---| 3 # 'Chest'
---| 4 # 'Groin'
---| 5 # 'Skirt'
---| 6 # 'RightHand'
---| 7 # 'LeftHand'
---| 8 # 'RightWrist'
---| 9 # 'LeftWrist'
---| 10 # 'Shield'
---| 11 # 'RightForearm'
---| 12 # 'LeftForearm'
---| 13 # 'RightUpperArm'
---| 14 # 'LeftUpperArm'
---| 15 # 'RightFoot'
---| 16 # 'LeftFoot'
---| 17 # 'RightAnkle'
---| 18 # 'LeftAnkle'
---| 19 # 'RightKnee'
---| 20 # 'LeftKnee'
---| 21 # 'RightUpperLeg'
---| 22 # 'LeftUpperLeg'
---| 23 # 'RightPauldron'
---| 24 # 'LeftPauldron'
---| 25 # 'Weapon'
---| 26 # 'Tail'

---@alias BodypartId
---| 'Head' # 0
---| 'Hair' # 1
---| 'Neck' # 2
---| 'Chest' # 3
---| 'Groin' # 4
---| 'Hand' # 5
---| 'Wrist' # 6
---| 'Forearm' # 7
---| 'UpperArm' # 8
---| 'Foot' # 9
---| 'Ankle' # 10
---| 'Knee' # 11
---| 'UpperLeg' # 12
---| 'Clavicle' # 13
---| 'Tail' # 14
---@alias BodypartType
---| 'Skin' 0
---| 'Clothing' 1
---| 'Armor' 2

---@alias BookType
---| 'Book' # 0
---| 'Scroll' # 1

---@alias ClothingType
---| 'Pants' # 0
---| 'Shoes' # 1
---| 'Shirt' # 2
---| 'Belt' # 3
---| 'Robe' # 4
---| 'RightGlove' # 5
---| 'LeftGlove' # 6
---| 'Skirt' # 7
---| 'Ring' # 8
---| 'Amulet' # 9

---@alias CreatureType
---| 'Normal' # 0
---| 'Daedra' # 1
---| 'Undead' # 2
---| 'Humanoid' # 3

---@alias EffectRange
---| 'OnSelf' # 0
---| 'OnTouch' # 1
---| 'OnTarget' 2

--- Awkward table representation of an inventory tuple
--- Inventory items are not unique, so, the inventory itself cannot be a hashmap,
--- Rather it is a vector of maps from recordIds to instance counts.
---@alias InventoryItem table<string, integer>

---@alias MagicEffectId
---| 'None' # -1
---| 'WaterBreathing' # 0
---| 'SwiftSwim' # 1
---| 'WaterWalking' # 2
---| 'Shield' # 3
---| 'FireShield' # 4
---| 'LightningShield' # 5
---| 'FrostShield' # 6
---| 'Burden' # 7
---| 'Feather' # 8
---| 'Jump' # 9
---| 'Levitate' # 10
---| 'SlowFall' # 11
---| 'Lock' # 12
---| 'Open' # 13
---| 'FireDamage' # 14
---| 'ShockDamage' # 15
---| 'FrostDamage' # 16
---| 'DrainAttribute' # 17
---| 'DrainHealth' # 18
---| 'DrainMagicka' # 19
---| 'DrainFatigue' # 20
---| 'DrainSkill' # 21
---| 'DamageAttribute' # 22
---| 'DamageHealth' # 23
---| 'DamageMagicka' # 24
---| 'DamageFatigue' # 25
---| 'DamageSkill' # 26
---| 'Poison' # 27
---| 'WeaknessToFire' # 28
---| 'WeaknessToFrost' # 29
---| 'WeaknessToShock' # 30
---| 'WeaknessToMagicka' # 31
---| 'WeaknessToCommonDisease' # 32
---| 'WeaknessToBlightDisease' # 33
---| 'WeaknessToCorprus' # 34
---| 'WeaknessToPoison' # 35
---| 'WeaknessToNormalWeapons' # 36
---| 'DisintegrateWeapon' # 37
---| 'DisintegrateArmor' # 38
---| 'Invisibility' # 39
---| 'Chameleon' # 40
---| 'Light' # 41
---| 'Sanctuary' # 42
---| 'NightEye' # 43
---| 'Charm' # 44
---| 'Paralyze' # 45
---| 'Silence' # 46
---| 'Blind' # 47
---| 'Sound' # 48
---| 'CalmHumanoid' # 49
---| 'CalmCreature' # 50
---| 'FrenzyHumanoid' # 51
---| 'FrenzyCreature' # 52
---| 'DemoralizeHumanoid' # 53
---| 'DemoralizeCreature' # 54
---| 'RallyHumanoid' # 55
---| 'RallyCreature' # 56
---| 'Dispel' # 57
---| 'SoulTrap' # 58
---| 'Telekinesis' # 59
---| 'Mark' # 60
---| 'Recall' # 61
---| 'DivineIntervention' # 62
---| 'AlmsiviIntervention' # 63
---| 'DetectAnimal' # 64
---| 'DetectEnchantment' # 65
---| 'DetectKey' # 66
---| 'SpellAbsorption' # 67
---| 'Reflect' # 68
---| 'CureCommonDisease' # 69
---| 'CureBlightDisease' # 70
---| 'CureCorprus' # 71
---| 'CurePoison' # 72
---| 'CureParalyzation' # 73
---| 'RestoreAttribute' # 74
---| 'RestoreHealth' # 75
---| 'RestoreMagicka' # 76
---| 'RestoreFatigue' # 77
---| 'RestoreSkill' # 78
---| 'FortifyAttribute' # 79
---| 'FortifyHealth' # 80
---| 'FortifyMagicka' # 81
---| 'FortifyFatigue' # 82
---| 'FortifySkill' # 83
---| 'FortifyMagickaMultiplier' # 84
---| 'AbsorbAttribute' # 85
---| 'AbsorbHealth' # 86
---| 'AbsorbMagicka' # 87
---| 'AbsorbFatigue' # 88
---| 'AbsorbSkill' # 89
---| 'ResistFire' # 90
---| 'ResistFrost' # 91
---| 'ResistShock' # 92
---| 'ResistMagicka' # 93
---| 'ResistCommonDisease' # 94
---| 'ResistBlightDisease' # 95
---| 'ResistCorprus' # 96
---| 'ResistPoison' # 97
---| 'ResistNormalWeapons' # 98
---| 'ResistParalysis' # 99
---| 'RemoveCurse' # 100
---| 'TurnUndead' # 101
---| 'SummonScamp' # 102
---| 'SummonClannfear' # 103
---| 'SummonDaedroth' # 104
---| 'SummonDremora' # 105
---| 'SummonGhost' # 106
---| 'SummonSkeleton' # 107
---| 'SummonLeastBonewalker' # 108
---| 'SummonGreaterBonewalker' # 109
---| 'SummonBonelord' # 110
---| 'SummonTwilight' # 111
---| 'SummonHunger' # 112
---| 'SummonGoldenSaint' # 113
---| 'SummonFlameAtronach' # 114
---| 'SummonFrostAtronach' # 115
---| 'SummonStormAtronach' # 116
---| 'FortifyAttackBonus' # 117
---| 'CommandCreature' # 118
---| 'CommandHumanoid' # 119
---| 'BoundDagger' # 120
---| 'BoundLongsword' # 121
---| 'BoundMace' # 122
---| 'BoundBattleAxe' # 123
---| 'BoundSpear' # 124
---| 'BoundLongbow' # 125
---| 'ExtraSpell' # 126
---| 'BoundCuirass' # 127
---| 'BoundHelm' # 128
---| 'BoundBoots' # 129
---| 'BoundShield' # 130
---| 'BoundGloves' # 131
---| 'Corprus' # 132
---| 'Vampirism' # 133
---| 'SummonCenturionSphere' # 134
---| 'SunDamage' # 135
---| 'StuntedMagicka' # 136
---| 'SummonFabricant' # 137
---| 'SummonWolf' # 138
---| 'SummonBear' # 139
---| 'SummonBoneWolf' # 140
---| 'Summon04' # 141
---| 'Summon05' # 142

---@alias SkillId2
---| 'None' -1
---| 'Block' 0
---| 'Armorer' 1
---| 'MediumArmor' 2
---| 'HeavyArmor' 3
---| 'BluntWeapon' 4
---| 'LongBlade' 5
---| 'Axe' 6
---| 'Spear' 7
---| 'Athletics' 8
---| 'Enchant' 9
---| 'Destruction' 10
---| 'Alteration' 11
---| 'Illusion' 12
---| 'Conjuration' 13
---| 'Mysticism' 14
---| 'Restoration' 15
---| 'Alchemy' 16
---| 'Unarmored' 17
---| 'Security' 18
---| 'Sneak' 19
---| 'Acrobatics' 20
---| 'LightArmor' 21
---| 'ShortBlade' 22
---| 'Marksman' 23
---| 'Mercantile' 24
---| 'Speechcraft' 25
---| 'HandToHand' 26

---@alias Specialization
---| 'None' # -1
---| 'Combat' # 0
---| 'Magic' # 1
---| 'Stealth' # 2

---@alias NormalizedPath string Lowercased string with unix-style paths
---@alias RecordId string 32-character limited string. Always lowercase.

---@class AIData
---@field alarm integer
---@field fight integer
---@field flee integer
---@field hello integer
---@field services integer

---@class AIActivate
---@field reset integer
---@field target RecordId
---@field type AIState

---@class AIEscort
---@field cell RecordId
---@field duration integer
---@field location number[]
---@field reset integer
---@field target RecordId
---@field type AIState

---@class AIFollow
---@field cell RecordId
---@field duration integer
---@field location number[]
---@field reset integer
---@field target RecordId
---@field type AIState

---@class AITravel
---@field location number[]
---@field reset number
---@field type AIState

---@class AIWander
---@field distance integer
---@field duration integer
---@field gameHour integer
---@field idle2 integer
---@field idle3 integer
---@field idle4 integer
---@field idle5 integer
---@field idle6 integer
---@field idle7 integer
---@field idle8 integer
---@field idle9 integer
---@field reset integer
---@field type AIState

---@class BaseRecord
---@field objectFlags integer Numeric flags with default value 0
---@field id RecordId Record editor identifier. Always lowercase.

--- Representation of an individual slot used by a clothing or armor
---@class BipedObject
---@field bipedObjectType BipedObjectType
---@field malePart RecordId? A BipedObject may omit defining parts at all simply to prevent another item from using that slot.
---@field femalePart RecordId? Female parts are optional

---@class ActivatorRecord: BaseRecord
---@field model NormalizedPath
---@field name? string
---@field script? RecordId

---@class ApparatusRecord: BaseRecord
---@field apparatusType ApparatusType
---@field icon NormalizedPath
---@field mesh NormalizedPath
---@field name string
---@field quality number
---@field script RecordId?
---@field value integer
---@field weight number

---@class ArmorRecord: BaseRecord
---@field armorRating integer
---@field armorType ArmorType
---@field durability integer
---@field enchantment RecordId?
---@field enchantmentValue integer
---@field icon NormalizedPath
---@field model NormalizedPath
---@field name string
---@field parts BipedObject[]
---@field script RecordId?
---@field weight number
---@field value integer

---@class BirthsignRecord: BaseRecord
---@field description string
---@field name string
---@field texture NormalizedPath
---@field spells RecordId[]

---@class BookRecord: BaseRecord
---@field bookType BookType
---@field enchantment RecordId
---@field enchantmentValue integer
---@field icon NormalizedPath
---@field model NormalizedPath
---@field name string
---@field script RecordId?
---@field skill SkillId2
---@field text string
---@field value integer
---@field weight number

---@class BodypartRecord: BaseRecord
---@field bodypartType BodypartType
---@field bodypartFlags integer
---@field part BodypartId
---@field race RecordId
---@field model NormalizedPath
---@field isVampire boolean?

---@class ClassRecord: BaseRecord
---@field attribute1 AttributeId2
---@field attribute2 AttributeId2
---@field classFlags integer
---@field major1 SkillId2
---@field major2 SkillId2
---@field major3 SkillId2
---@field major4 SkillId2
---@field major5 SkillId2
---@field minor1 SkillId2
---@field minor2 SkillId2
---@field minor3 SkillId2
---@field minor4 SkillId2
---@field minor5 SkillId2
---@field services integer
---@field specialization Specialization

---@class ClothingRecord: BaseRecord
---@field clothingType ClothingType
---@field enchantment RecordId?
---@field enchantmentValue integer
---@field icon NormalizedPath
---@field model NormalizedPath
---@field name string
---@field parts BipedObject[]
---@field script RecordId?
---@field weight number
---@field value integer

---@class ContainerRecord: BaseRecord
---@field capacity number
---@field containerFlags integer
---@field inventory InventoryItem[]
---@field model NormalizedPath
---@field name string
---@field script RecordId?

---@class CreatureRecord: BaseRecord
---@field AIData AIData
---@field AIPackages AIPackage[]
---@field agility integer
---@field attack1Min integer
---@field attack1Max integer
---@field attack2Min integer
---@field attack2Max integer
---@field attack3Min integer
---@field attack3Max integer
---@field baseGold integer
---@field bloodType integer
---@field combatAbility integer
---@field creatureFlags integer
---@field creatureType CreatureType
---@field endurance integer
---@field fatigue integer
---@field health integer
---@field intelligence integer
---@field inventory InventoryItem[]
---@field level integer
---@field luck integer
---@field magicAbility integer
---@field magicka integer
---@field model NormalizedPath
---@field name string
---@field personality integer
---@field scale number?
---@field script RecordId?
---@field soulValue integer
---@field sound RecordId
---@field speed integer
---@field spells RecordId[]
---@field stealthAbility integer
---@field strength integer
---@field travelDestinations TravelDestination[]
---@field willpower integer

---@class MagicEffect
---@field area integer
---@field attribute AttributeId2
---@field duration integer
---@field magicEffect MagicEffectId
---@field maxMagnitude integer
---@field minMagnitude integer
---@field range EffectRange
---@field skill SkillId2

---@class PotionRecord: BaseRecord
---@field effects MagicEffect[]
---@field icon NormalizedPath
---@field name string
---@field model NormalizedPath
---@field potionFlags integer
---@field script RecordId?
---@field value integer
---@field weight number

---@class StaticRecord: BaseRecord
---@field model NormalizedPath

---@class TravelDestination
---@field cell RecordId
---@field posX number
---@field posY number
---@field posZ number
---@field rotX number
---@field rotY number
---@field rotZ number

---@class RecordStores
---@field Activator table<RecordId, ActivatorRecord>
---@field Apparatus table<RecordId, ApparatusRecord>
---@field Armor table<RecordId, ArmorRecord>
---@field Alchemy table<RecordId, PotionRecord>
---@field Birthsign table<RecordId, BirthsignRecord>
---@field BodyPart table<RecordId, BodypartRecord>
---@field Book table<RecordId, BookRecord>
---@field Class table<RecordId, ClassRecord>
---@field Clothing table<RecordId, ClothingRecord>
---@field Container table<RecordId, ContainerRecord>
---@field Creature table<RecordId, CreatureRecord>
---@field Static table<RecordId, StaticRecord>
