---@meta

---@alias MWGender 0|1 0 indicates female, 1 is male

---@alias MWRace
---| 'argonian'
---| 'breton'
---| 'dark elf'
---| 'high elf'
---| 'imperial'
---| 'khajiit'
---| 'nord'
---| 'orc'
---| 'redguard'
---| 'wood elf'

---@alias CellDescription string Name of a cell as defined by content files
---@alias CommandTokens string[] pre-tokenized command string provided to all commandHandlers. The first value is always the name of the command entered, excluding the leading slash, and will always be lowercase.
---@alias CommandHandler fun(pid: PlayerId, cmd: CommandTokens) Special function type for handling chat commands
---@alias ContentFixMap table<CellDescription, ContentFixType>
---@alias DataFileRequirements table<string, string[]>
---@alias GUIID integer Unique numeric Identifier for GUIs
---@alias Inventory Item[]
---@alias PlayerId integer zero-based integer indicating a unique player ID.
---@alias RefNum integer reference to a unique reference number defined by content files

---@alias OSType
---| 'Windows'
---| 'Linux'
---| 'OS X'
---| 'Unknown OS' -- This one probably shouldn't happen!

---@class ContentFixType
---@field disable RefNum[]?
---@field unlock RefNum[]?

---@class Item
---@field enchantmentCharge integer -1 if not enchanted.
---@field soul string soul inhabiting an enchanted item. Must be present, but may be empty.
---@field refId string recordId of an inventory item
---@field count integer Number of items in a particular item stack. Must be at least 1.
---@field charge integer -1 if not enchanted.

---@class stringlib
---@field split fun(self: string, separator: string): string[] Splits a string by a separator and returns an array of matching substrings
---@field trim fun(self: string): string Removes whitespace from the beginning and end of a string
---@field capitalizeFirstLetter fun(self: string): string
---@field ciEqual fun(self: string, otherString: string): boolean case-insensitive equality comparison
---@field prefixZeroes fun(self: string, desiredLength: integer): string Given a number of zeroes to prefix, returns the original string with N zeroes prepended
---@field normalize fun(self: string): string lowercases and converts all backslashes to forward slashes
---@field titleCase fun(self: string): string

---@class TES3MPCommand
---@field definedBy string path of the script which defined this command. The name of the script which defines a command it kept so that old references to it may be removed.
---@field callback CommandHandler handler function for whenever this command is invoked
---@field nameRequirement string[]? optional list of exclusive names which may run a given command
---@field rankRequirement integer? optional rank requirement to run a command

---@class TES3MPModule
---Add a new client global integer to the client globals.
---@field AddClientGlobalInteger fun(id: RecordId, intValue: integer, variableType?: integer)
---Add a new client global float to the client globals.
---@field AddClientGlobalFloat fun(id: RecordId, floatValue: number)
---Add a new cooldown spell to the cooldown changes for a player.
---@field AddCooldownSpell fun(pid: PlayerId, spellId: RecordId, startDay: integer, startHour: number)
---Set a rule string for the server details displayed in the server browser.
---@field AddDataFileRequirement fun(dataFilename: string, checksumString: string)
---Add a new kill count to the kill count changes.
---@field AddKill fun(refId: RecordId, number: integer)
---Add a copy of the server's temporary record of the current specified type to the stored records.
---@field AddRecord fun()
---Add a copy of the server's temporary body part to the temporary record of the current specified type.
---@field AddRecordBodyPart fun()
---Add a copy of the server's temporary effect to the temporary record of the current specified type.
---@field AddRecordEffect fun()
---Add a copy of the server's temporary inventory item to the temporary record of the current specified type.
---@field AddRecordInventoryItem fun()
---Add a new spell to the spellbook changes for a player.
---@field AddSpell fun(pid: PlayerId, spellId: RecordId)
---Add a new active spell to the spells active changes for a player, using the temporary effect values stored so far.
---@field AddSpellActive fun(pid: PlayerId, spellId: RecordId, displayName: string, stackingState: boolean)
---Add a new effect to the next active spell that will be added to a player.
---@field AddSpellActiveEffect fun(pid: PlayerId, effectId: integer, magnitude: number, duration: number, timeLeft: number, arg: integer)
---Add an ID to the list of script IDs whose variable changes should be sent to the server by clients.
---@field AddSynchronizedClientScriptId fun(scriptId: RecordId)
---Add an ID to the list of global IDs whose value changes should be sent to the server by clients.
---@field AddSynchronizedClientGlobalId fun(globalId: RecordId)
---Add a refId to the list of refIds for which collision should be enforced irrespective of other settings.
---@field AddEnforcedCollisionRefId fun(refId: RecordId)
---Add a cell with given cellDescription to the list of cells that should be reset on the client.
---@field AddCellToReset fun(cellDescription: CellDescription)
---Add a destination override containing the cell description for the old cell and the new cell.
---@field AddDestinationOverride fun(oldCellDescription: CellDescription, newCellDescription: CellDescription)
---@field BanAddress fun(ipAddress: string) Given an IP Address string, bans it. Doesn't perform any validation, so caller functions need to do so themselves.
---Clear the modifier value of a player's attribute.
---@field ClearAttributeModifier fun(pid: PlayerId, attributeId: integer)
---Clear the list of cells which should be reset on the client.
---@field ClearCellsToReset fun()
---Clear the client globals for the write-only worldstate.
---@field ClearClientGlobals fun()
---Clear the last recorded cooldown changes for a player.
---@field ClearCooldownChanges fun(pid: PlayerId)
---Clear the list of destination overrides.
---@field ClearDestinationOverrides fun()
---Clear the list of refIds for which collision should be enforced irrespective of other settings.
---@field ClearEnforcedCollisionRefIds fun()
---@field ClearGameSettingValues fun(pid: PlayerId) Clears game setting values for a specific player, undoing changes made by calls to SetGameSetting
---Clear the kill count changes for the write-only worldstate.
---@field ClearKillChanges fun()
---Clear the map changes for the write-only worldstate.
---@field ClearMapChanges fun()
---Clear the data from the records stored on the server.
---@field ClearRecords fun()
---Clear the modifier value of a player's skill.
---@field ClearSkillModifier fun(pid: PlayerId, skillId: integer)
---Clear the last recorded spellbook changes for a player.
---@field ClearSpellbookChanges fun(pid: PlayerId)
---Clear the last recorded spells active changes for a player.
---@field ClearSpellsActiveChanges fun(pid: PlayerId)
---Clear the list of script IDs whose variable changes should be sent to the server by clients.
---@field ClearSynchronizedClientScriptIds fun()
---Clear the list of global IDs whose value changes should be sent to the server by clients.
---@field ClearSynchronizedClientGlobalIds fun()
---@field ClearVRSettingValues fun(pid: PlayerId) Clears VR game setting values for a specific player, undoing changes made by calls to SetGameSetting
---Take the contents of the read-only worldstate last received by the server from a player and move its contents to the stored worldstate that can be sent by the server.
---@field CopyReceivedWorldstateToStore fun()
---@field CustomMessageBox fun(pid: PlayerId, id: integer, label: string, items: string) Displays a multiple-choice message box to the target PID
---Check whether a certain file path exists.
---@field DoesFilePathExist fun(filePath: string): boolean
---Check whether the spell at a certain index in a player's latest spells active changes has a player as its caster.
---@field DoesSpellsActiveHavePlayerCaster fun(pid: PlayerId, index: integer): boolean
---Get the architecture type used by the server.
---@field GetArchitectureType fun(): string
---Get the base value of a player's attribute.
---@field GetAttributeBase fun(pid: PlayerId, attributeId: integer): integer
---Get the number of attributes.
---@field GetAttributeCount fun(): integer
---Get the amount of damage (as caused through the Damage Attribute effect) to a player's attribute.
---@field GetAttributeDamage fun(pid: PlayerId, attributeId: integer): number
---Get the numerical ID of an attribute with a certain name.
---@field GetAttributeId fun(name: string): integer
---Get the modifier value of a player's attribute.
---@field GetAttributeModifier fun(pid: PlayerId, attributeId: integer): integer
---Get the name of the attribute with a certain numerical ID.
---@field GetAttributeName fun(attributeId: integer): string
---@field GetAvgPing fun(pid: PlayerId): integer returns a specific player's average ping
---Get the birthsign of a player.
---@field GetBirthsign fun(pid: PlayerId): string
---Get the bounty of the player.
---@field GetBounty fun(pid: PlayerId): integer
---Searches a subfolder for the first file with a name whose matches `fileName` case-insensitively, and returns its path if found
---@field GetCaseInsensitiveFilename fun(folderPath: string, fileName: string): string
---Get the number of indexes in the read worldstate's client globals.
---@field GetClientGlobalsSize fun(): integer
---Get the float value of the global variable at a certain index in the read worldstate's client globals.
---@field GetClientGlobalFloatValue fun(index: integer): number
---Get the integer value of the global variable at a certain index in the read worldstate's client globals.
---@field GetClientGlobalIntValue fun(index: integer): integer
---Get the id of the global variable at a certain index in the read worldstate's client globals.
---@field GetClientGlobalId fun(index: integer): RecordId
---Get the type of the global variable at a certain index in the read worldstate's client globals.
---@field GetClientGlobalVariableType fun(index: integer): integer
---Get the number of indexes in a player's latest cooldown changes.
---@field GetCooldownChangesSize fun(pid: PlayerId): integer
---Get the spell id at a certain index in a player's latest cooldown changes.
---@field GetCooldownSpellId fun(pid: PlayerId, index: integer): RecordId
---Get the starting day of the cooldown at a certain index in a player's latest cooldown changes.
---@field GetCooldownStartDay fun(pid: PlayerId, index: integer): integer
---Get the starting hour of the cooldown at a certain index in a player's latest cooldown changes.
---@field GetCooldownStartHour fun(pid: PlayerId, index: integer): number
---Check whether a player's name is replaced by that of the creature they are disguised as when other players hover over them.
---@field GetCreatureNameDisplayState fun(pid: PlayerId): boolean
---Get the refId of the creature the player is disguised as.
---@field GetCreatureRefId fun(pid: PlayerId): RecordId
---Get the data file enforcement state of the server.
---@field GetDataFileEnforcementState fun(): boolean
---Get the path of the server's data folder.
---@field GetDataPath fun(): string
---Get the base fatigue of the player.
---@field GetFatigueBase fun(pid: PlayerId): number
---Get the current fatigue of the player.
---@field GetFatigueCurrent fun(pid: PlayerId): number
---Get the hairstyle mesh used by a player.
---@field GetHairstyle fun(pid: PlayerId): string
---Get the head mesh used by a player.
---@field GetHead fun(pid: PlayerId): string
---Get the base health of the player.
---@field GetHealthBase fun(pid: PlayerId): number
---Get the current health of the player.
---@field GetHealthCurrent fun(pid: PlayerId): number
---Get the IP address of a certain player.
---@field GetIP fun(pid: PlayerId): string
---Check whether a player is male or not.
---@field GetIsMale fun(pid: PlayerId): integer
---Get the number of indexes in the read worldstate's kill changes.
---@field GetKillChangesSize fun(): integer
---Get the number of kills at a certain index in the read worldstate's kill count changes.
---@field GetKillNumber fun(index: integer): integer
---Get the refId at a certain index in the read worldstate's kill count changes.
---@field GetKillRefId fun(index: integer): RecordId
---@field GetLastPlayerId fun(): PlayerId returns the last PID which connected to the server
---Get the character level of a player.
---@field GetLevel fun(pid: PlayerId): integer
---Get the player's progress to their next character level.
---@field GetLevelProgress fun(pid: PlayerId): integer
---Get the base magicka of the player.
---@field GetMagickaBase fun(pid: PlayerId): number
---Get the current magicka of the player.
---@field GetMagickaCurrent fun(pid: PlayerId): number
---Get the number of indexes in the read worldstate's map changes.
---@field GetMapChangesSize fun(): integer
---Get the X coordinate of the cell corresponding to the map tile at a certain index in the read worldstate's map tiles.
---@field GetMapTileCellX fun(index: integer): integer
---Get the Y coordinate of the cell corresponding to the map tile at a certain index in the read worldstate's map tiles.
---@field GetMapTileCellY fun(index: integer): integer
---Get the maximum number of players.
---@field GetMaxPlayers fun(): integer
---Get the milliseconds elapsed since the server was started.
---@field GetMillisecondsSinceServerStart fun(): integer
---Get the model of a player.
---@field GetModel fun(pid: PlayerId): string
---Get the name of a player.
---@field GetName fun(pid: PlayerId): string
---@field GetOperatingSystemType fun(): OSType
---Get the port used by the server.
---@field GetPort fun(): integer
---Get the protocol version of the server.
---@field GetProtocolVersion fun(): string
---Get the race of a player.
---@field GetRace fun(pid: PlayerId): string
---Get the auto-calculation flag value of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordAutoCalc fun(index: integer): integer
---Get the base id (i.e. the id this record should inherit default values from) of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordBaseId fun(index: integer): RecordId
---Get the charge of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordCharge fun(index: integer): integer
---Get the cost of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordCost fun(index: integer): integer
---Get the number of records in the read worldstate's dynamic records.
---@field GetRecordCount fun(): integer
---Get the area of the effect at a certain index in the read worldstate's current records.
---@field GetRecordEffectArea fun(recordIndex: integer, effectIndex: integer): integer
---Get the ID of the attribute modified by the effect at a certain index in the read worldstate's current records.
---@field GetRecordEffectAttribute fun(recordIndex: integer, effectIndex: integer): integer
---Get the number of effects for the record at a certain index in the read worldstate's current records.
---@field GetRecordEffectCount fun(recordIndex: integer): integer
---Get the duration of the effect at a certain index in the read worldstate's current records.
---@field GetRecordEffectDuration fun(recordIndex: integer, effectIndex: integer): integer
---Get the ID of the effect at a certain index in the read worldstate's current records.
---@field GetRecordEffectId fun(recordIndex: integer, effectIndex: integer): integer
---Get the maximum magnitude of the effect at a certain index in the read worldstate's current records.
---@field GetRecordEffectMagnitudeMax fun(recordIndex: integer, effectIndex: integer): integer
---Get the minimum magnitude of the effect at a certain index in the read worldstate's current records.
---@field GetRecordEffectMagnitudeMin fun(recordIndex: integer, effectIndex: integer): integer
---Get the range type of the effect at a certain index in the read worldstate's current records.
---@field GetRecordEffectRangeType fun(recordIndex: integer, effectIndex: integer): integer
---Get the ID of the skill modified by the effect at a certain index in the read worldstate's current records.
---@field GetRecordEffectSkill fun(recordIndex: integer, effectIndex: integer): integer
---Get the enchantment charge of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordEnchantmentCharge fun(index: integer): integer
---Get the enchantment id of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordEnchantmentId fun(index: integer): RecordId
---Get the flags of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordFlags fun(index: integer): integer
---Get the icon of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordIcon fun(index: integer): string
---Get the id of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordId fun(index: integer): RecordId
---Get the model of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordModel fun(index: integer): string
---Get the name of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordName fun(index: integer): string
---Get the quantity of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordQuantity fun(index: integer): integer
---Get the script of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordScript fun(index: integer): string
---Get the subtype of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordSubtype fun(index: integer): integer
---Get the type of records in the read worldstate's dynamic records.
---@field GetRecordType fun(): integer
---Get the value of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordValue fun(index: integer): integer
---Get the weight of the record at a certain index in the read worldstate's dynamic records of the current type.
---@field GetRecordWeight fun(index: integer): number
---Get the scale of a player.
---@field GetScale fun(pid: PlayerId): number
---Get the script error ignoring state of the server.
---@field GetScriptErrorIgnoringState fun(): boolean
---Get the TES3MP version of the server.
---@field GetServerVersion fun(): string
---@field GetSHA256Hash fun(input: string): string Given some string input, hashes it
---Get the base value of a player's skill.
---@field GetSkillBase fun(pid: PlayerId, skillId: integer): integer
---Get the number of skills.
---@field GetSkillCount fun(): integer
---Get the amount of damage (as caused through the Damage Skill effect) to a player's skill.
---@field GetSkillDamage fun(pid: PlayerId, skillId: integer): number
---Get the numerical ID of a skill with a certain name.
---@field GetSkillId fun(name: string): integer
---Get the bonus applied to a certain attribute at the next level up as a result of associated skill increases.
---@field GetSkillIncrease fun(pid: PlayerId, attributeId: integer): integer
---Get the modifier value of a player's skill.
---@field GetSkillModifier fun(pid: PlayerId, skillId: integer): integer
---Get the name of the skill with a certain numerical ID.
---@field GetSkillName fun(skillId: integer): string
---Get the progress the player has made towards increasing a certain skill by 1.
---@field GetSkillProgress fun(pid: PlayerId, skillId: integer): number
---Get the action type used in a player's latest spellbook changes.
---@field GetSpellbookChangesAction fun(pid: PlayerId): integer
---Get the number of indexes in a player's latest spellbook changes.
---@field GetSpellbookChangesSize fun(pid: PlayerId): integer
---Get the spell id at a certain index in a player's latest spellbook changes.
---@field GetSpellId fun(pid: PlayerId, index: integer): RecordId
---Get the mpNum of the actor caster of the spell at a certain index in a player's latest spells active changes.
---@field GetSpellsActiveCasterMpNum fun(pid: PlayerId, index: integer): integer
---Get the player ID of the caster of the spell at a certain index in a player's latest spells active changes.
---@field GetSpellsActiveCasterPid fun(pid: PlayerId, index: integer): integer
---Get the refId of the actor caster of the spell at a certain index in a player's latest spells active changes.
---@field GetSpellsActiveCasterRefId fun(pid: PlayerId, index: integer): RecordId
---Get the refNum of the actor caster of the spell at a certain index in a player's latest spells active changes.
---@field GetSpellsActiveCasterRefNum fun(pid: PlayerId, index: integer): integer
---Get the action type used in a player's latest spells active changes.
---@field GetSpellsActiveChangesAction fun(pid: PlayerId): integer
---Get the number of indexes in a player's latest spells active changes.
---@field GetSpellsActiveChangesSize fun(pid: PlayerId): integer
---Get the spell display name at a certain index in a player's latest spells active changes.
---@field GetSpellsActiveDisplayName fun(pid: PlayerId, index: integer): string
---Get the arg for an effect index at a spell index in a player's latest spells active changes.
---@field GetSpellsActiveEffectArg fun(pid: PlayerId, spellIndex: integer, effectIndex: integer): integer
---Get the number of effects at an index in a player's latest spells active changes.
---@field GetSpellsActiveEffectCount fun(pid: PlayerId, index: integer): integer
---Get the duration for an effect index at a spell index in a player's latest spells active changes.
---@field GetSpellsActiveEffectDuration fun(pid: PlayerId, spellIndex: integer, effectIndex: integer): number
---Get the id for an effect index at a spell index in a player's latest spells active changes.
---@field GetSpellsActiveEffectId fun(pid: PlayerId, spellIndex: integer, effectIndex: integer): integer
---Get the magnitude for an effect index at a spell index in a player's latest spells active changes.
---@field GetSpellsActiveEffectMagnitude fun(pid: PlayerId, spellIndex: integer, effectIndex: integer): number
---Get the time left for an effect index at a spell index in a player's latest spells active changes.
---@field GetSpellsActiveEffectTimeLeft fun(pid: PlayerId, spellIndex: integer, effectIndex: integer): number
---Get the spell id at a certain index in a player's latest spells active changes.
---@field GetSpellsActiveId fun(pid: PlayerId, index: integer): RecordId
---Get the spell stacking state at a certain index in a player's latest spells active changes.
---@field GetSpellsActiveStackingState fun(pid: PlayerId, index: integer): boolean
---Get the current weather in the read worldstate.
---@field GetWeatherCurrent fun(): integer
---Get the next weather in the read worldstate.
---@field GetWeatherNext fun(): integer
---Get the queued weather in the read worldstate.
---@field GetWeatherQueued fun(): integer
---Get the weather region in the read worldstate.
---@field GetWeatherRegion fun(): string
---Get the transition factor of the weather in the read worldstate.
---@field GetWeatherTransitionFactor fun(): number
---Checking if the server requires a password to connect.
---@field HasPassword fun(): boolean
---@field InputDialog fun(pid: PlayerId, id: GUIID, label: string, note: string) Displays an input dialog
---Check whether a player is a werewolf.
---@field IsWerewolf fun(pid: PlayerId): boolean
---Kick a certain player from the server.
---@field Kick fun(pid: PlayerId)
---Load a .png file as the image data for a map tile and add it to the write-only worldstate stored on the server.
---@field LoadMapTileImageFile fun(cellX: integer, cellY: integer, filePath: string)
---@field LogMessage fun(logLevel: LogLevel, logMessage: string) Emits a message to the server log & stdout at the provided log level
---@field LogAppend fun(logLevel: LogLevel, logMessage: string) Emits a message to the server log & stdout at the provided log level
---@field PasswordDialog fun(pid: PlayerId, id: GUIID, label: string, note: string) Displays an input dialog whose inputs are displayed only as asterisks
---@field PlaySpeech fun(pid: PlayerId, speechPath: string) Plays a voice file for all players on the server. Intended to be used with speechHelper interface
---Use the last worldstate received by the server as the one being read.
---@field ReadReceivedWorldstate fun()
---Save the .png image data of the map tile at a certain index in the read worldstate's map changes.
---@field SaveMapTileImageFile fun(index: integer, filePath: string)
---Send a PlayerAttribute packet with a player's attributes and bonuses to those attributes at the next level up.
---@field SendAttributes fun(pid: PlayerId)
---Send a PlayerBaseInfo packet with a player's name, race, head mesh, hairstyle mesh, birthsign and stat reset state.
---@field SendBaseInfo fun(pid: PlayerId)
---Send a PlayerBounty packet with a player's bounty.
---@field SendBounty fun(pid: PlayerId)
---Send a CellReset packet with a list of cells.
---@field SendCellReset fun(pid: PlayerId, sendToOtherPlayers: boolean)
---Send a ClientScriptGlobal packet with the current client script globals in the write-only worldstate.
---@field SendClientScriptGlobal fun(pid: PlayerId, sendToOtherPlayers?: boolean, skipAttachedPlayer?: boolean)
---Send a ClientScriptSettings packet with the current client script settings in the write-only worldstate.
---@field SendClientScriptSettings fun(pid: PlayerId, sendToOtherPlayers?: boolean, skipAttachedPlayer?: boolean)
---Send a PlayerCooldowns packet with a player's recorded cooldown changes.
---@field SendCooldownChanges fun(pid: PlayerId)
---Send a PlayerLevel packet with a player's character level and progress towards the next level up.
---@field SendLevel fun(pid: PlayerId)
---@field SendMessage fun(pid: PlayerId, message: string, sendToAll: boolean?) Emits a chat message to a specific player, optionally relaying it to all players
---Send a RecordDynamic packet with the current specified record type.
---@field SendRecordDynamic fun(pid: PlayerId, sendToOtherPlayers?: boolean, skipAttachedPlayer?: boolean)
---@field SendSettings fun(pid: PlayerId, sendToAll: boolean, skipAttachedPlayer: boolean) After constructing a settings packet using `SetEnforcedLogLevel`, `SetPhysicsFramerate`, SetGameSettingValue`, `SetVRSettingValue`, or `SetDifficulty`, send it to players, optionally including or omitting all players or just the `pid` provided
---Send a PlayerShapeshift packet about a player.
---@field SendShapeshift fun(pid: PlayerId)
---Send a PlayerSkill packet with a player's skills.
---@field SendSkills fun(pid: PlayerId)
---Send a PlayerSpellbook packet with a player's recorded spellbook changes.
---@field SendSpellbookChanges fun(pid: PlayerId, sendToOtherPlayers?: boolean, skipAttachedPlayer?: boolean)
---Send a PlayerSpellsActive packet with a player's recorded spells active changes.
---@field SendSpellsActiveChanges fun(pid: PlayerId, sendToOtherPlayers?: boolean, skipAttachedPlayer?: boolean)
---Send a PlayerStatsDynamic packet with a player's dynamic stats (health, magicka and fatigue).
---@field SendStatsDynamic fun(pid: PlayerId)
---Send a WorldCollisionOverride packet with the current collision overrides in the write-only worldstate.
---@field SendWorldCollisionOverride fun(pid: PlayerId, sendToOtherPlayers?: boolean, skipAttachedPlayer?: boolean)
---Send a WorldDestinationOverride packet with the current destination overrides in the write-only worldstate.
---@field SendWorldDestinationOverride fun(pid: PlayerId, sendToOtherPlayers?: boolean, skipAttachedPlayer?: boolean)
---Send a WorldKillCount packet with the current set of kill count changes in the write-only worldstate.
---@field SendWorldKillCount fun(pid: PlayerId, sendToOtherPlayers?: boolean, skipAttachedPlayer?: boolean)
---Send a WorldMap packet with the current set of map changes in the write-only worldstate.
---@field SendWorldMap fun(pid: PlayerId, sendToOtherPlayers?: boolean, skipAttachedPlayer?: boolean)
---Send a WorldRegionAuthority packet establishing a certain player as the only one who should process certain region-specific events (such as weather changes).
---@field SendWorldRegionAuthority fun(pid: PlayerId)
---Send a WorldTime packet with the current time and time scale in the write-only worldstate.
---@field SendWorldTime fun(pid: PlayerId, sendToOtherPlayers?: boolean, skipAttachedPlayer?: boolean)
---Send a WorldWeather packet with the current weather in the write-only worldstate.
---@field SendWorldWeather fun(pid: PlayerId, sendToOtherPlayers?: boolean, skipAttachedPlayer?: boolean)
---Set the collision state for actors in the write-only worldstate stored on the server.
---@field SetActorCollisionState fun(state: boolean)
---Set the base value of a player's attribute.
---@field SetAttributeBase fun(pid: PlayerId, attributeId: integer, value: integer)
---Set the amount of damage (as caused through the Damage Attribute effect) to a player's attribute.
---@field SetAttributeDamage fun(pid: PlayerId, attributeId: integer, value: number)
---Set the region affected by the next WorldRegionAuthority packet sent.
---@field SetAuthorityRegion fun(authorityRegion: string)
---@field SetBedRestAllowed fun(pid: PlayerId, bedAllowed: boolean) Set whether or not a specific player may use beds
---Set the birthsign of a player.
---@field SetBirthsign fun(pid: PlayerId, name: string)
---Set the bounty of a player.
---@field SetBounty fun(pid: PlayerId, value: integer)
---Set the current and ending stages of character generation for a player.
---@field SetCharGenStage fun(pid: PlayerId, currentStage: integer, endStage: integer)
---@field SetConsoleAllowed fun(pid: PlayerId, consoleAllowed: boolean) Set whether or not a specific player may use the console
---Set whether a player's name is replaced by that of the creature they are disguised as when other players hover over them.
---@field SetCreatureNameDisplayState fun(pid: PlayerId, displayState: boolean)
---Set the refId of the creature a player is disguised as.
---@field SetCreatureRefId fun(pid: PlayerId, refId: RecordId)
---Set the data file enforcement state of the server.
---@field SetDataFileEnforcementState fun(state: boolean)
---Set the world's day in the write-only worldstate stored on the server.
---@field SetDay fun(day: integer)
---Set the world's days passed in the write-only worldstate stored on the server.
---@field SetDaysPassed fun(daysPassed: integer)
---@field SetDifficulty fun(pid: PlayerId, difficulty: integer) Changes the difficulty for a player, but does NOT send a packet. Use SendSettings to notify clients of difficulty changes.--
---@field SetEnforcedLogLevel fun(pid: PlayerId, logLevel: LogLevel) Sets the enforced log level for a player. Doesn't send a packet on its own. Log level enforcement is important to prevent players from receiving information about world state they otherwise would not. Use a logLevel of -1 not to enforce this setting.
---Set the base fatigue of a player.
---@field SetFatigueBase fun(pid: PlayerId, value: number)
---Set the current fatigue of a player.
---@field SetFatigueCurrent fun(pid: PlayerId, value: number)
---Set the game mode of the server, as displayed in the server browser.
---@field SetGameMode fun(gameMode: string)
---@field SetGameSettingValue fun(pid: PlayerId, gameSetting: string, value: any) Override a setting from the `Game` category of settings.cfg. For valid settings and values, refer to here: https://openmw.readthedocs.io/en/openmw-0.47.0_a/reference/modding/settings/game.html
---Set the hairstyle mesh used by a player.
---@field SetHairstyle fun(pid: PlayerId, hairstyle: string)
---Set the head mesh used by a player.
---@field SetHead fun(pid: PlayerId, head: string)
---Set the base health of a player.
---@field SetHealthBase fun(pid: PlayerId, value: number)
---Set the current health of a player.
---@field SetHealthCurrent fun(pid: PlayerId, value: number)
---Set the name of the server, as displayed in the server browser.
---@field SetHostname fun(name: string)
---Set the world's hour in the write-only worldstate stored on the server.
---@field SetHour fun(hour: number)
---Set whether a player is male or not.
---@field SetIsMale fun(pid: PlayerId, state: integer)
---Set the character level of a player.
---@field SetLevel fun(pid: PlayerId, value: integer)
---Set the player's progress to their next character level.
---@field SetLevelProgress fun(pid: PlayerId, value: integer)
---Set the base magicka of a player.
---@field SetMagickaBase fun(pid: PlayerId, value: number)
---Set the current magicka of a player.
---@field SetMagickaCurrent fun(pid: PlayerId, value: number)
---Set the (animation) model of a player.
---@field SetModel fun(pid: PlayerId, model: string)
---Set the world's month in the write-only worldstate stored on the server.
---@field SetMonth fun(month: integer)
---Set the name of a player.
---@field SetName fun(pid: PlayerId, name: string)
---@field SetPhysicsFramerate fun(pid: PlayerId, framerate: integer) Sets the physics framerate for a specific client. Doesn't send a packet. Use SendSettings to notify clients of changes.
---Set the collision state for placed objects in the write-only worldstate stored on the server.
---@field SetPlacedObjectCollisionState fun(state: boolean)
---Set the collision state for other players in the write-only worldstate stored on the server.
---@field SetPlayerCollisionState fun(state: boolean)
---Set the race of a player.
---@field SetRace fun(pid: PlayerId, race: string)
---Set the AI alarm value of the temporary record stored on the server for the currently specified record type.
---@field SetRecordAIAlarm fun(aiAlarm: integer)
---Set the AI fight value of the temporary record stored on the server for the currently specified record type.
---@field SetRecordAIFight fun(aiFight: integer)
---Set the AI flee value of the temporary record stored on the server for the currently specified record type.
---@field SetRecordAIFlee fun(aiFlee: integer)
---Set the AI services value of the temporary record stored on the server for the currently specified record type.
---@field SetRecordAIServices fun(aiServices: integer)
---Set the armor rating of the temporary record stored on the server for the currently specified record type.
---@field SetRecordArmorRating fun(armorRating: integer)
---Set the auto-calculation flag value of the temporary record stored on the server for the currently specified record type.
---@field SetRecordAutoCalc fun(autoCalc: integer)
---Set the base id (i.e. the id this record should inherit default values from) of the temporary record stored on the server for the currently specified record type.
---@field SetRecordBaseId fun(baseId: RecordId)
---Set the blood type of the temporary record stored on the server for the currently specified record type.
---@field SetRecordBloodType fun(bloodType: integer)
---Set the body part type of the temporary body part stored on the server.
---@field SetRecordBodyPartType fun(partType: integer)
---Set the id of the female version of the temporary body part stored on the server.
---@field SetRecordBodyPartIdForFemale fun(partId: RecordId)
---Set the id of the male version of the temporary body part stored on the server.
---@field SetRecordBodyPartIdForMale fun(partId: RecordId)
---Set the character class of the temporary record stored on the server for the currently specified record type.
---@field SetRecordClass fun(charClass: string)
---Set the closing sound of the temporary record stored on the server for the currently specified record type.
---@field SetRecordCloseSound fun(sound: string)
---Set the color of the temporary record stored on the server for the currently specified record type.
---@field SetRecordColor fun(red: integer, green: integer, blue: integer)
---Set the charge of the temporary record stored on the server for the currently specified record type.
---@field SetRecordCharge fun(charge: integer)
---Set the cost of the temporary record stored on the server for the currently specified record type.
---@field SetRecordCost fun(cost: integer)
---Set the chop damage of the temporary record stored on the server for the currently specified record type.
---@field SetRecordDamageChop fun(minDamage: integer, maxDamage: integer)
---Set the slash damage of the temporary record stored on the server for the currently specified record type.
---@field SetRecordDamageSlash fun(minDamage: integer, maxDamage: integer)
---Set the thrust damage of the temporary record stored on the server for the currently specified record type.
---@field SetRecordDamageThrust fun(minDamage: integer, maxDamage: integer)
---Set the area of the temporary effect stored on the server.
---@field SetRecordEffectArea fun(area: integer)
---Set the ID of the attribute modified by the temporary effect stored on the server.
---@field SetRecordEffectAttribute fun(attributeId: integer)
---Set the duration of the temporary effect stored on the server.
---@field SetRecordEffectDuration fun(duration: integer)
---Set the ID of the temporary effect stored on the server.
---@field SetRecordEffectId fun(effectId: integer)
---Set the maximum magnitude of the temporary effect stored on the server.
---@field SetRecordEffectMagnitudeMax fun(magnitudeMax: integer)
---Set the minimum magnitude of the temporary effect stored on the server.
---@field SetRecordEffectMagnitudeMin fun(magnitudeMin: integer)
---Set the range type of the temporary effect stored on the server.
---@field SetRecordEffectRangeType fun(rangeType: integer)
---Set the ID of the skill modified by the temporary effect stored on the server.
---@field SetRecordEffectSkill fun(skillId: integer)
---Set the enchantment charge of the temporary record stored on the server for the currently specified record type.
---@field SetRecordEnchantmentCharge fun(enchantmentCharge: integer)
---Set the enchantment id of the temporary record stored on the server for the currently specified record type.
---@field SetRecordEnchantmentId fun(enchantmentId: RecordId)
---Set the enchantment id of the record at a certain index in the records stored on the server.
---@field SetRecordEnchantmentIdByIndex fun(index: integer, enchantmentId: RecordId)
---Set the faction of the temporary record stored on the server for the currently specified record type.
---@field SetRecordFaction fun(faction: string)
---Set the fatigue of the temporary record stored on the server for the currently specified record type.
---@field SetRecordFatigue fun(fatigue: integer)
---Set the flags of the temporary record stored on the server for the currently specified record type.
---@field SetRecordFlags fun(flags: integer)
---Set the float variable of the temporary record stored on the server for the currently specified record type.
---@field SetRecordFloatVariable fun(floatVar: number)
---Set the gender of the temporary record stored on the server for the currently specified record type.
---@field SetRecordGender fun(gender: integer)
---Set the hair of the temporary record stored on the server for the currently specified record type.
---@field SetRecordHair fun(hair: string)
---Set the head of the temporary record stored on the server for the currently specified record type.
---@field SetRecordHead fun(head: string)
---Set the health of the temporary record stored on the server for the currently specified record type.
---@field SetRecordHealth fun(health: integer)
---Set the icon of the temporary record stored on the server for the currently specified record type.
---@field SetRecordIcon fun(icon: string)
---Set the id of the temporary record stored on the server for the currently specified record type.
---@field SetRecordId fun(id: RecordId)
---Set the id of the record at a certain index in the records stored on the server.
---@field SetRecordIdByIndex fun(index: integer, id: RecordId)
---Set the inventory base id of the temporary record stored on the server for the currently specified record type.
---@field SetRecordInventoryBaseId fun(inventoryBaseId: RecordId)
---Set the count of the temporary inventory item stored on the server.
---@field SetRecordInventoryItemCount fun(count: integer)
---Set the id of the temporary inventory item stored on the server.
---@field SetRecordInventoryItemId fun(itemId: RecordId)
---Set the integer variable of the temporary record stored on the server for the currently specified record type.
---@field SetRecordIntegerVariable fun(intVar: integer)
---Set whether the temporary record stored on the server for the currently specified record type is a key.
---@field SetRecordKeyState fun(keyState: boolean)
---Set the level of the temporary record stored on the server for the currently specified record type.
---@field SetRecordLevel fun(level: integer)
---Set the magicka of the temporary record stored on the server for the currently specified record type.
---@field SetRecordMagicka fun(magicka: integer)
---Set the maximum range of the temporary record stored on the server for the currently specified record type.
---@field SetRecordMaxRange fun(maxRange: number)
---Set the minimum range of the temporary record stored on the server for the currently specified record type.
---@field SetRecordMinRange fun(minRange: number)
---Set the model of the temporary record stored on the server for the currently specified record type.
---@field SetRecordModel fun(model: string)
---Set the name of the temporary record stored on the server for the currently specified record type.
---@field SetRecordName fun(name: string)
---Set the opening sound of the temporary record stored on the server for the currently specified record type.
---@field SetRecordOpenSound fun(sound: string)
---Set the quality of the temporary record stored on the server for the currently specified record type.
---@field SetRecordQuality fun(quality: number)
---Set the race of the temporary record stored on the server for the currently specified record type.
---@field SetRecordRace fun(race: string)
---Set the radius of the temporary record stored on the server for the currently specified record type.
---@field SetRecordRadius fun(radius: integer)
---Set the reach of the temporary record stored on the server for the currently specified record type.
---@field SetRecordReach fun(reach: number)
---Set whether the temporary record stored on the server for the currently specified record type is a scroll.
---@field SetRecordScrollState fun(scrollState: boolean)
---Set the scale of the temporary record stored on the server for the currently specified record type.
---@field SetRecordScale fun(scale: number)
---Set the script of the temporary record stored on the server for the currently specified record type.
---@field SetRecordScript fun(script: string)
---Set the script text of the temporary record stored on the server for the currently specified record type.
---@field SetRecordScriptText fun(scriptText: string)
---Set the skill ID of the temporary record stored on the server for the currently specified record type.
---@field SetRecordSkillId fun(skillId: integer)
---Set the soul value of the temporary record stored on the server for the currently specified record type.
---@field SetRecordSoulValue fun(soulValue: integer)
---Set the sound of the temporary record stored on the server for the currently specified record type.
---@field SetRecordSound fun(sound: string)
---Set the speed of the temporary record stored on the server for the currently specified record type.
---@field SetRecordSpeed fun(speed: number)
---Set the string variable of the temporary record stored on the server for the currently specified record type.
---@field SetRecordStringVariable fun(stringVar: string)
---Set the subtype of the temporary record stored on the server for the currently specified record type.
---@field SetRecordSubtype fun(subtype: integer)
---Set the text of the temporary record stored on the server for the currently specified record type.
---@field SetRecordText fun(text: string)
---Set the time of the temporary record stored on the server for the currently specified record type.
---@field SetRecordTime fun(time: integer)
---Set the type of records in the read worldstate's dynamic records.
---@field SetRecordType fun(type: integer)
---Set the number of uses of the temporary record stored on the server for the currently specified record type.
---@field SetRecordUses fun(uses: integer)
---Set the value of the temporary record stored on the server for the currently specified record type.
---@field SetRecordValue fun(value: integer)
---Set the vampire state of the temporary record stored on the server for the currently specified record type.
---@field SetRecordVampireState fun(vampireState: boolean)
---Set the volume of the temporary record stored on the server for the currently specified record type.
---@field SetRecordVolume fun(volume: number)
---Set the weight of the temporary record stored on the server for the currently specified record type.
---@field SetRecordWeight fun(weight: number)
---Set whether the player's stats should be reset based on their current race as the result of a PlayerBaseInfo packet.
---@field SetResetStats fun(pid: PlayerId, resetStats: boolean)
---Set a rule string for the server details displayed in the server browser.
---@field SetRuleString fun(key: string, value: string)
---Set a rule value for the server details displayed in the server browser.
---@field SetRuleValue fun(key: string, value: number)
---Set the scale of a player.
---@field SetScale fun(pid: PlayerId, scale: number)
---Set the script error ignoring state of the server.
---@field SetScriptErrorIgnoringState fun(state: boolean)
---Set the base value of a player's skill.
---@field SetSkillBase fun(pid: PlayerId, skillId: integer, value: integer)
---Set the amount of damage (as caused through the Damage Skill effect) to a player's skill.
---@field SetSkillDamage fun(pid: PlayerId, skillId: integer, value: number)
---Set the bonus applied to a certain attribute at the next level up as a result of associated skill increases.
---@field SetSkillIncrease fun(pid: PlayerId, attributeId: integer, value: integer)
---Set the progress the player has made towards increasing a certain skill by 1.
---@field SetSkillProgress fun(pid: PlayerId, skillId: integer, value: number)
---Set the password required to join the server.
---@field SetServerPassword fun(password: string)
---Set the action type in a player's spellbook changes.
---@field SetSpellbookChangesAction fun(pid: PlayerId, action: integer)
---Set the action type in a player's spells active changes.
---@field SetSpellsActiveChangesAction fun(pid: PlayerId, action: integer)
---Set the world's time scale in the write-only worldstate stored on the server.
---@field SetTimeScale fun(timeScale: number)
---@field SetVRSettingValue fun(pid: PlayerId, vrSetting: string, value: any) Override a setting from the `VR` category of settings.cfg. For valid settings and values, refer to here: https://openmw.readthedocs.io/en/openmw-0.47.0_a/reference/modding/settings/game.html
---@field SetWaitAllowed fun(pid: PlayerId, waitAllowed: boolean) Set whether or not a specific player may wait
---Set the current weather in the write-only worldstate stored on the server.
---@field SetWeatherCurrent fun(currentWeather: integer)
---Set the weather forcing state in the write-only worldstate stored on the server.
---@field SetWeatherForceState fun(forceState: boolean)
---Set the next weather in the write-only worldstate stored on the server.
---@field SetWeatherNext fun(nextWeather: integer)
---Set the queued weather in the write-only worldstate stored on the server.
---@field SetWeatherQueued fun(queuedWeather: integer)
---Set the weather region in the write-only worldstate stored on the server.
---@field SetWeatherRegion fun(region: string)
---Set the transition factor for the weather in the write-only worldstate stored on the server.
---@field SetWeatherTransitionFactor fun(transitionFactor: number)
---Set the werewolf state of a player.
---@field SetWerewolfState fun(pid: PlayerId, isWerewolf: boolean)
---@field SetWildernessRestAllowed fun(pid: PlayerId, wildernessRestAllowed: boolean) Set whether or not a specific player may rest in the wilderness
---Set the world's year in the write-only worldstate stored on the server.
---@field SetYear fun(year: integer)
---@field StopServer fun(exitCode: integer) Terminate the server with a provided exit code
---@field UnbanAddress fun(ipAddress: string) Given an IP Address string, unbans it. Doesn't perform any validation, so caller functions need to do so themselves.
---Whether placed objects with collision turned on should use actor collision, i.e. whether they should be slippery and prevent players from standing on them.
---@field UseActorCollisionForPlacedObjects fun(useActorCollision: boolean)
tes3mp = tes3mp
